services:
  pgadmin:
    image: ${PGADMIN_IMAGE:-dpage/pgadmin4:9.18}
    container_name: pgadmin4
    restart: unless-stopped
    network_mode: host
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_DISABLE_POSTFIX: "1"
      PGADMIN_LISTEN_ADDRESS: "127.0.0.1"
      PGADMIN_LISTEN_PORT: "5050"
      PGADMIN_CONFIG_SERVER_MODE: "True"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  pgadmin-data:
